name: 'dbt_exo'
version: 1.0.0
config-version: 2
profile: 'default'

models:
  dbt_exo:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    mart:
      +materialized: table